name: ci

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: run linter
        run: |
          pip install flake8
          flake8 app.py
  test:
    strategy:
      matrix:
        python-versions: ['3.11', '3.12', '3.13']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-versions }}
      - name: run pytest
        run: |
          pip install pytest flask
          pytest