name: ci

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: run linter
        run: |
          pip install flake8
          flake8 app.py